LogsPolicy:
  Type: AWS::IAM::Policy
  Properties:
    PolicyName: !Sub "${StackName}-logs-policy"
    Users:
      - !Ref IamUser
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
